<?php
/**
 * Copyright 2019 aheadWorks. All rights reserved.
See LICENSE.txt for license details.
 */

/** @var $block \Aheadworks\Layerednav\Block\Filter\Item\Renderer */
/** @var $filterItem \Aheadworks\Layerednav\Model\Layer\Filter\ItemInterface */
/** @var \Aheadworks\Layerednav\ViewModel\SelectedFilters\FilterItemRenderer $viewModel */
$viewModel = $block->getViewModel();

$renderType = $viewModel->getRenderType($filterItem);
$filterRenderer = $viewModel->getRendererBlock($block->getLayout(), $block->getNameInLayout(), $renderType);
// @codingStandardsIgnoreFile
?>
<?= /* @noEscape */ $filterRenderer ? $filterRenderer->render($filterItem) : '' ?>
